-- Create Quizzes Table
CREATE TABLE quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  total_questions INTEGER DEFAULT 0,
  duration_minutes INTEGER DEFAULT 60,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Questions Table
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES quizzes(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL, -- Array of {label, text}
  correct_answer TEXT NOT NULL,
  teras TEXT DEFAULT 'General',
  explanation TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Attempts Table (For simple tracking without Auth first)
CREATE TABLE attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT, 
  quiz_id BIGINT REFERENCES quizzes(id),
  score INTEGER,
  answers JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS (Row Level Security) - Optional for now but good practice
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempts ENABLE ROW LEVEL SECURITY;

-- Allow public read access to quizzes and questions (since auth is not fully implemented yet)
CREATE POLICY "Public quizzes are viewable by everyone" ON quizzes FOR SELECT USING (true);
CREATE POLICY "Public questions are viewable by everyone" ON questions FOR SELECT USING (true);
CREATE POLICY "Public attempts can be inserted" ON attempts FOR INSERT WITH CHECK (true);
